### ISSUE TITLE
[meta] make user registration fully functional

### ISSUE THREAD

**Issue by MaHaWo** [ssciwr/mondey-frontend-prototype#24]
this is largely the same as the children registration, but it might be better to first do this with local variables and then add a user store in another PR 
- [x] rework the current registration page to get overly complex abstraction out of the way. 
- [x] user registration must be functional: 
 - [x] password verification 
 - [x] local variable need to hold new user 
 - [x] new user data needs to be addable 
 - [x] new user data needs to be verified 
 - [x] children store must get a new user.
